//
// Generated file, do not edit! Created by nedtool 5.0 from PositionPacket.msg.
//

#ifndef __POSITIONPACKET_M_H
#define __POSITIONPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>PositionPacket.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // Position message
 * //
 * packet PositionPacket
 * {
 *     int id;
 *     double x;
 *     double y;
 *     double time;
 * }
 * </pre>
 */
class PositionPacket : public ::omnetpp::cPacket
{
  protected:
    int id;
    double x;
    double y;
    double time;

  private:
    void copy(const PositionPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PositionPacket&);

  public:
    PositionPacket(const char *name=nullptr, int kind=0);
    PositionPacket(const PositionPacket& other);
    virtual ~PositionPacket();
    PositionPacket& operator=(const PositionPacket& other);
    virtual PositionPacket *dup() const {return new PositionPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
    virtual double getTime() const;
    virtual void setTime(double time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PositionPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PositionPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __POSITIONPACKET_M_H

